### ISSUE TITLE
Menu items cannot be reordered without erroneous nesting

### ISSUE THREAD

**Issue by jwilson8767** [rainlab/pages-plugin#109]
When dragging menu items to reorder they are nested in error. I request either up/down reorder buttons or margin be added between each item. I tested setting `.control-treeview ol > li {margin-bottom:5px;}`, but found that it does not work when dealing with reordering nested items. Adding `.control-treeview li.has-items{margin-bottom:5px;}` allowed for reordering nesting and top level items, however the extra spaces do not present well and I am unsure if this is really the best solution.

As you can see in this image, one cannot set the "Reserve now" item between the first and second item:
![image](https://cloud.githubusercontent.com/assets/10873576/10717802/6c4cc8c4-7b39-11e5-947a-416df1aae8f3.png)

(on a side note, I have opened this issue on the pages-plugin repo instead of the october repo because the issue is affecting me here and is easily replicated using the pages-plugin, though I realize the treeview control is part of the october backend and style changes will probably end up there)

**Comment by gavinfostered** [comment]
Hi, if you grab the page and drag all the way to the right of the screen the page being dragged should turn into a dotted red line instead of a blue block allowing you to more easily drop pages "between" pages instead of accidentally nesting them, which I agree is way too easy to do. Screenshot attached. Hope that helps.

![screen shot 2015-10-27 at 15 29 40](https://cloud.githubusercontent.com/assets/2064358/10762908/cb4be21a-7cbf-11e5-9991-ae49468b1a47.png)

**Comment by jwilson8767** [comment]
Doesn't work on my site. Also the treeview on the side menu is so narrow that reordering there is nearly impossible without accidentally nesting.

**Comment by daftspunk** [comment]
Can someone submit a pull request that fixes this?

**Comment by daftspunk** [comment]
This should be fixed in https://github.com/octobercms/october/commit/6bae91b411923b17015364babd3eb4b7132c5fab

Available in Build 335+
