### ISSUE TITLE
There are some case with looping on generation breadcrumbs

### ISSUE THREAD

**Issue by evgemar** [rainlab/pages-plugin#117]
Maximum execution time of 30 seconds exceeded
plugins/rainlab/pages/components/StaticBreadcrumbs.php on line 51
##

**Comment by side-by-side** [comment]
Hi, #156 is all abot this.
Like a temporary workaround the default language in `/config/app.php` should match your backend choosen language.

**Comment by NickMChambers** [comment]
This problem occurs with the latest build, even with the locale set to 'en'.

**Comment by daftspunk** [comment]
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Comment by jasonridesabike** [comment]
+1. Also getting this issue

A repeated timeout occurs on all front end pages on line 50 or 51 of StaticBreadcrumbs.php, but not from the backend.

I'm not sure how reproducible this will be across installations, but for me it occurs on every front end page.

**Comment by LukeTowers** [comment]
Hmm, that loop looks suspicious to me. If you could provide a replication of your setup (i.e. what pages are where and how they're structured, and then the layout file for the pages that you're seeing this issue on the frontend on) then that would be helpful. @jasonridesabike

**Comment by LukeTowers** [comment]
Fixed by #277
