### ISSUE TITLE
Customize markupcode of snippet created from component

### ISSUE THREAD

**Issue by ametad** [rainlab/pages-plugin#131]
First of all: nice plugin and good work!

My problem..
Because of AJAX handling functionality for a contact form snippet, I needed a snippet created from a component. The component handles AJAX. But because of [limitations (link)](http://octobercms.com/docs/cms/partials#life-cycle-limitations) it is not possible to put this component on a partial and in turn create a snippet out of that partial. 

Normally you can customize the markupcode of a component by 'forking' it in a partial or layout. Then the markupcode can be customized! But how can I customize the markupcode of a snippet created from component for a particular theme?

Snippet created from component in the Plugin definition class:

``` php
public function registerPageSnippets()
{
    return [
       '\RainLab\Weather\Components\Weather' => 'weather'
    ];
}
```

**Comment by Harti** [comment]
did you find a solution?

**Comment by ametad** [comment]
Sorry Harti, 
For it has been too long ago, I cannot remember... I closed it for my own administration so it wouldn't bother me anymore.

**Comment by LukeTowers** [comment]
The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Post a bug bounty](https://www.bountysource.com/teams/october) for this specific issue so that more people can become involved with creating a fix
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone
