### ISSUE TITLE
Feature request: permission per page

### ISSUE THREAD

**Issue by vanmil** [rainlab/pages-plugin#135]
Hi,

Would it be possible to give specific administrators the permission to manage specific static pages and others not? 
Currently it is only possible in the backend to allow or deny an administrator the permission to manage **all** the static pages.

Thanks in advance :)

**Comment by LukeTowers** [comment]
Please only use GitHub Issues for feature requests if you are using it as a pre-Pull Request collaboration tool. If you aren't planning on implementing it yourself, then it would be better suited being asked for on one of these channels:

Forum: http://octobercms.com/forum
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/

The support demand for October is increasing, while the available time the founders have to give remains the same. Feature requests are by default the lowest priority for us, as we don't have time to implement everyone's suggestions by ourselves. However there are ways you can help:

- Submit a pull request that introduces this feature and we'll review it. Please note that the amount of effort making the PR (code quality, rationale for inclusion in the project, explanation of changes) is directly proportional to the likelihood that we will review and merge it.
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

Closing as it has been over a month since any activity on this occurred.
