### ISSUE TITLE
Page Rendering

### ISSUE THREAD

**Issue by HendrikBoone** [rainlab/pages-plugin#136]
Don't know what I'm doing wrong, but the content of pages (written using this plugin) is rendered twice.
Tried another theme but the result is the same.

**Comment by hybridvision** [comment]
It's strange that it would persist with a different theme but check your layouts where the plugin is integrated and make sure you only have one `{% page %}` code in the layout. Also ensure you only have the static pages component included once.

**Comment by HendrikBoone** [comment]
Guess I found the problem. I've created a layout with the page plugin component as needed, so you can start using the wysiwyg interface. When I remove `{% page %}` in the code, the text is only rendered once. When inserted, the text is doubled.

So basically  `{% page %}` is replaced with `{% component 'staticPage' %}`. Hope that this is the way it should be done.

**Comment by hybridvision** [comment]
I have it the other way around: no `{% component 'staticPage' %}` in the layout code (although it is added to the configuration section). I think this is the better way because `{% page %}` is for the standard content and other plugins potentially. Maybe for your use it doesn't make a difference but you might have a problem later with non-static pages...
