### ISSUE TITLE
Content loss with layout change

### ISSUE THREAD

**Issue by daftpirate** [rainlab/pages-plugin#210]
Since October stores content in flat files (and I like it in many ways), there is a problem that if curious client changes Static Page Layout and goes back it will lose all content set in `partials` and `variables`.

For now i rely on backup, but this *can* cause a problem some day.

Is there a way to disable Layout change for certain pages? 
Or are there some best practices for this case?

**Comment by CptMeatball** [comment]
Switching layouts also seems to empty localised fields #212

**Comment by daftspunk** [comment]
Need something clear cut to follow, with expected and actual results. As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by daftpirate** [comment]
**Summary:** if you change layout, you lose content from all fields generated by layout, only main Content tab will remain.

1. Create static layout with some `{% variable1 %}` or `{% partial tab2 %}`. Example: `layouts/static/test.htm`.
2. Create static page, choose created layout. `Test page`.
3. Fill with some content our main tab, variable and partial. `content/static-pages/test-page.htm` file have content like:
```
[viewBag]
title = "Test page"
url = "/test-page"
layout = "static/test"
is_hidden = 0
navigation_hidden = 0
variable1 = "Variable text"
==
{% put tab2 %}
<p>Second tab text</p>
{% endput %}
==
<p>Main content</p>
```
4. Choose other Layout (Test 2) for this page and save - all content from variables and partials is gone. `content/static-pages/test-page.htm' looks like: 

```
[viewBag]
title = "Test page"
url = "/test-page"
layout = "static/test"
is_hidden = 0
navigation_hidden = 0
==
<p>Main content</p>
```

It's logical behavior, because we have content stored in .htm file and it can't leave "unneeded" content after layout is changed and file is saved. 

But potential problem is that client or content manager can try to change layout and lose his content. 
> Curiosity killed the cat.

So it isn't really bug report, more like looking for advice - what is better to do to prevent curious user from losing his content? We all know warning is simple not enough.

**Comment by daftspunk** [comment]
Perhaps for existing pages, changing the layout should have a prompt when saving, something like:

> Are you sure you want to save with a different layout? This may cause loss of existing content.

**Comment by tbergeron** [comment]
Just curious @daftpirate if I encountered the same bug. I've been searching around for a while.

On normal CMS pages all my localizations are there (see the top nav): http://d.pr/i/WjTf
But once I switched to a rainlab-pages static page my nav loses all its locales: http://d.pr/i/qXzD

Content stays localized but the static page top nav and page titles stops being localized (page title is now "Certifications - site.name"). Sounds the same to me, agreed? Thanks!

**Comment by seffw** [comment]
Is this issue solved? It suggests OctoberCMS is far from ready for production use when content can be lost through backend action like this.

@daftspunk, was that whole '_Need something clear cut to follow, with expected and actual results. As per the contribution guidelines, please provide .....'_'  really necessary? It just delayed a vital issue that was obvious from the original post

**Comment by daftspunk** [comment]
There is nothing actionable from this. See Log settings > Theme logging on data loss prevention. Available in Build 401+

**Comment by LukeTowers** [comment]
@seffw We are very busy, and there are a lot of tasks that require our attention. If we can't clearly understand what is being said the first time round we will ask for further information to clarify the issue because we don't have time to spend trying to understand the situation with the initially provided information. The more information you provide, and the more clear that you can be, the faster we can help with the issue.

**Comment by seffw** [comment]
@LukeTowers  Sure, and i know how encompassing such open source projects can be. But the issue was clear from the first post, and could have been tested and confirmed in less time than the poster spent 'following the rules'.

I think a better response would have been 'Thanks for identifying such a major flaw which we missed. Well done', if you want a better system were participants are encouraged to report issues and get involved and help with the workload

**Comment by seffw** [comment]
@daftspunk  Don't get why you closed this issue. You made the original poster spend time explaining all of it then shut it down. This issues needs to be open so others don't lose work. Care about your users.

**Comment by LukeTowers** [comment]
@seffw Not sure why you seem to be so offended by this, we didn't issue any 'warning', simply a request for more information. You seem to be awfully concerned on @daftpirate's behalf and I'm not 100% sure why. 

I still don't see what we would to do prevent this issue, I haven't heard any suggestions from anyone involved, just vague accusations of having a "bad vibe". If you would like to provide suggestions for how this behaviour could be improved to bring it more in line with users' expectations, then go ahead. This may seem like an obvious bug to you, but you need to take the time to explain how it affects you and your ideas for improving the current behaviour instead of putting the onus on us to just "solve our users problems". 

For me, any work I put into this project is entirely volunteer and I do what I can when I can. If people want assistance with their issues, then they need to put in as much effort as possible to so that I can spend as little time as possible reviewing it; otherwise the issue will get looked at when I have the time to get to it. Due to the scale of the project, and my current inability to clone myself, I can't take care of everything at once, so I don't think it's unreasonable to ask for further clarification. 

@daftspunk's original reply wasn't about the original post being so unclear that we can't figure out what the issue is, it was about requesting more information so that we can spend less time deciphering the problem and generating ideas for solutions and then implementing them.

We could for sure figure out what the issue was and implement a solution for it without any further information, but why would we spend the time doing that when there are other higher priority issues that other people have put more effort into working on solutions for that also demand our attention?

Have patience and put in the effort to help find a solution instead of just demanding that we drop everything and take care of your problems. Remember, you are not paying us for support, we are not in a business relationship with you, so keep that in mind whenever you think we're not handling something the way you want it to be done.

**Comment by seffw** [comment]
@LukeTowers  I was trying to make the point that highlighting issues matters. This was an issue that I also saw. Assumptions that I am offended, too concerned or anything else is irrelevant. In case it matters, I don't know the original poster, I just saw the same major obvious flaw in October. 

Did I ask for support? And for what it's worth, I'm a team member of an open source project you might know, so I understand about volunteering and the work involved.

What October needs to do is separate content from theme and layout. Otherwise it is behind in almost every other CMS in one of the most important areas. If this got sorted out, it has potential to be one of the best with a lot more users than it has now.

So before you think I have some alterer motive. I do. I'm trying to make the point that a major mistake has been made about how content, layout and theme should behave and this thread was the first I saw (other than my own) that addressed a part of it.

I would say the solution in principal is straight forward. Have any user generated content (CMS-> Content, Pages->Page, Pages->Content) outside the theme / template folder. This would solve two issues. The one here and also allow themes to be changed while keeping user content (which is also a major issue as every other CMS I've used allows theme changes while keeping all content)

**Comment by LukeTowers** [comment]
Please don't hijack other issues to push your own preferences, keep your discussion on the topic of how October architects its content data within the previous thread that you created (#237). The decision to structure the content the way it has been (i.e. within themes) was a conscious one and results from October's goal of "back to basics" and originating as a flat file CMS.

You seem to be offended by the fact that this route has been chosen, so I'm not going to try to convince you otherwise. Again, continue this discussion in #237 instead of cross posting in other issues. Another issue that this has been discussed in is #100 for further reference.

**Comment by seffw** [comment]
For goodness sake get over yourself. I started supporting the issue of the thread. Stop trying to turn it into something else. I'm deleting my posts here as you have misrepresented my posts

**Comment by daftspunk** [comment]
I don't want to get in to a heated debate about this guys. When you change the layout, it modifies the scaffold of the page, of course there will be data loss as a result. We have introduced theme logging which should take care of it. The issue was replicated and proposal was made but not accepted by anyone. 

This issue has completely lost focus so I've closed it, apologies if there are any outstanding concerns or issues, simply log another issue with a nice succient description and we can take another look.
