### ISSUE TITLE
Placeholder tabs appear within 'Settings' which confuses clients.

### ISSUE THREAD

**Issue by NickMChambers** [rainlab/pages-plugin#247]
When adding a Placeholder to create an editable area, the resulting tab appears within 'Settings'.

This is very confusing for clients and doesn't follow the normal pattern when using other Content Management Systems.

If the tabs appeared at the top level (i.e. next to 'Meta'), rather than within 'Settings', it would improve usability immensely.

**Comment by jan-vince** [comment]
At first I didn't want to answer to your issue as I do not use placeholders much, but today I saw how confused my client was, when I was showing her, how to edit custom fields in backend.

I mostly use {variable} to add custom fields because Partials only support html and text and I quite often need repeater, switch, dropdown, ...

All {variable} fields are placed in tabs next to Meta tab (which is maybe a solution to your issue ?).

But what I am fighting with is the original Content tab that is shown in secondary tabs row below Meta and {variable} tabs. This is quite confusing when you edit some content on first line tabs and other content on the second one.

So I added to [my plugin](https://octobercms.com/plugin/janvince-smallextensions) option to completely hide default Content tab (*it is nothing special - just hide it with css and stretch first line box*).

Now I can use only {variable} fields and Static Page editor is looking much more simple. Just one line of tabs.

Maybe this is also a way how to solve your problem?

**Comment by jeremymouton** [comment]
We've developed an in-house plugin to improve the Static Pages plugin for our clients and move those tabs to the same level as "Content".

It's unofficial, but you can find it here: https://github.com/aspendigital/october-lookfeel
(Place it in `plugins/aspendigital/lookfeel`)

Then in your layout you can use variables, repeaters...

`{variable name="custom_content" label="Custom Content" tab="Custom Content" size="giant" type="richeditor"}{/variable}`

It currently supports variables, richeditor, text, repeater, and radio fields.

![screen shot 2017-04-05 at 2 49 31 pm](https://cloud.githubusercontent.com/assets/1574433/24726336/4e2a947c-1a0f-11e7-99bd-9140e430a0e5.png)

Let us know if you end up using it or if you run into any issues.

**Comment by NickMChambers** [comment]
@jan-vince I thought about using variables and I agree that the tabs do appear within the correct place.

However, my client is actually going to be editing the HTML files (I know) in a text editor and as variables store the whole content within quotation marks, I thought it was much easier to use Placeholders.

I even wondered if there was some way to get placeholders within CMS pages to appear as separate tabs within the Backend Edit pages, but that didn't work at all.

It's so frustrating, because October CMS is such an excellent system and I'm trying to pursuade people to use it instead of WordPress, but little quirks like this really put people off and make it illogical to use.

**Comment by LukeTowers** [comment]
@jeremymouton Have you considered getting some of those improvements merged into the rainlab.pages plugin directly? I know the interface of the plugin as it is right now could use some improvements and your implementation looks nice.

**Comment by daftspunk** [comment]
I think we all agree with the sentiments here. I'd like to add something: The team at AspenDigital do great work! Notably https://github.com/octobercms/october/pull/2277.

This plugin belongs to everyone guys, so if there are improvements that can be made without hurting anyone, let's get them in as Pull Requests. If there are breaking changes that need to be made, we can still work it in using [important updates](http://octobercms.com/docs/plugin/updates#important-updates).

Another cool idea to consider: Add a property to the `StaticPage` component called `hideContent` which would essentially disable the Content tab, declaring that the page has no content section, allowing it to be "settings only" -- powered by placeholders and syntax fields alone.

**Comment by jeremymouton** [comment]
@LukeTowers @daftspunk We're planning on merging it in. Haven't gotten there yet, but I'll discuss with the team and we'll send a PR.

Our LookFeel plugin does support `noContent` already, you can set `hideContentField = true` in the layout file to hide the default "Content" wysiwyg (Documented here: https://github.com/aspendigital/october-lookfeel#hide-layout-content-markup-field).

**Comment by jan-vince** [comment]
@NickMChambers Not sure what you are trying to do :(

I always keep my clients far from code and almost everything they need can be done inside Pages plugin backend forms/fields.

{variable} allows me to add even complex logic, so maybe you can also find a way how to use them instead of editing files (or limit this to content files which can be accessed from Pages backend).

@jeremymouton 's plugin looks great and can help a lot in keeping clients inside Pages plugin!

**Comment by NickMChambers** [comment]
@jan-vince OK, well if you're managing fine using {variable} then that's great and this issue obviously doesn't affect you.

Personally, I still think that it's illogical for the Placeholder tabs to appear within 'Settings'.

**Comment by jimcottrell** [comment]
Thanks for the shout-out, @daftspunk.  I think we were possibly a little too tentative about making UX changes for everyone, but we had some sticking points we wanted to address for our clients.  Clearly there's some broader appeal there, so I'll put together some pull requests to bring functionality from our plugin into the Static Pages plugin itself.

**Comment by jimcottrell** [comment]
On re-reading this issue, I don't know if this particular issue is actually addressed by any of our customizations.  It sounds like this could be a misunderstanding about there being two independent sets of tabs (see @NickMChambers mentioning placeholder tabs appearing *within* "Settings"), though displaying the content, placeholders, and variable tabs at the same level like we do via our plugin does add some consistency.

Maybe this issue really has the solution of, say, a border or an <hr> in between the primary and secondary tabs (when both are visible) to visually clarify the page elements.

**Comment by daftspunk** [comment]
I think it makes sense that the top primary tabs area should be reserved for settings introduced by extending PHP code. The secondary tabs should be exclusively used for content -- including placeholders and syntax fields. This is because the primary tab area can be collapsed, and if so, some important content areas could be missed by a client.

AFAIK the syntax fields are added to the primary tab area, this should be changed to be the secondary tab area. This will create a more consistent UX as the client doesn't make a distinction between content, placeholders and syntax fields -- it's all content to them.

**Comment by LukeTowers** [comment]
@daftspunk So placeholders, syntax fields, and main page content should all be located in the secondaryTabs area then?

**Comment by daftspunk** [comment]
Yeah that's what we're all kind of saying here, right? Perhaps @NickMChambers might be referring to "syntax fields" instead of "placeholders". Placeholders currently sit in the secondary tab area, not the primary.

**Comment by jan-vince** [comment]
@daftspunk To have everything "content related" in secondaryTab area makes perfect sense to me.

It is quite hard to explain to clients that some content has to be changed in first line tabs and other in the secondary one.

*Maybe you can add an option like {variable placement="primary"} to allow non default placement - as some fields can be Settings related. That would make it more flexible.*

**Comment by NickMChambers** [comment]
Just to clarify, I'm definitely referring to Placeholders (as per the title of this issue).

![placeholders](https://cloud.githubusercontent.com/assets/6270545/24789178/bdc5b5b8-1b69-11e7-9a6b-62da5d919d8e.gif)

The 'Settings' tab should be reserved for things like selecting the layout or ticking checkboxes ('Hidden', 'Hidden in navigation' etc).

Actually, when the Settings tab is closed, then the Placeholder tabs appear where expected.

![placeholders2](https://cloud.githubusercontent.com/assets/6270545/24789407/d286ad80-1b6a-11e7-856a-3435206a77f5.gif)

Maybe it's as simple as making all tabs appear 'top level' - Settings, Meta, Content, Placeholder1, Placeholder2 etc.

There's plenty of room and that would solve the problem as far as making it less confusing for clients/users.

**Comment by daftspunk** [comment]
This is fixed by #248. Simple solution in @NickMChambers' case is to collapse the settings tabs. This is fairly easy to teach to a client and is a common pattern throughout the CMS.

Thanks @jimcottrell, look forward to seeing more!

**Comment by seanthepottingshed** [comment]
Hello my lovelies, 

Any chance of implementing: 

_Maybe you can add an option like **{variable placement="primary"}** to allow non default placement - as some fields can be Settings related. That would make it more flexible._

**Comment by jan-vince** [comment]
I have created PR rainlab/pages-plugin#262 to address this as I have many custom fields related to settings/meta more than a content.

**Comment by seanthepottingshed** [comment]
@jan-vince LEGEND!

**Comment by jBOKA** [comment]
Seems not to be deployed through october's marketplace yet. See
https://github.com/rainlab/pages-plugin/pull/252
