### ISSUE TITLE
Translated URLs containing non-ASCII characters won't be set active in the menu when visited

### ISSUE THREAD

**Issue by manuelbua** [rainlab/pages-plugin#261]
#### Steps to reproduce the bug

- install the `Static Pages` plugin
- activate two languages, ie. **English** and **Deutsch**
- setup the menu in the layout
- create a static page, fill-in the title and some placeholder content
- for the URL, set anything for the **English** one, then use `ausflüge` for the **German** one
- visit the page at both URLS: you'll notice that the English URL will be rendered as active, while the German one will not be

#### Description

This happens because the comparison is performed without decoding encoded chars such as `%C3%BC` for the `ü` character, and for some reason the hex code points are being compared uppercase vs lowercase.

One solution may be to force the casing via `Str::lower`, or maybe decoding the characters via `rawurldecode`.

[This is the line](https://github.com/rainlab/pages-plugin/blob/23b9bc09ba48a8144c99698de296982d05f8c47e/classes/Page.php#L750) on the `Page.php` class inside the pages plugin.

I'm not sure if this can be solved by merely wrapping both values within the `rawurldecode` PHP function:

```php
// from this
$result['isActive'] = $result['url'] == $url;

// to this
$result['isActive'] = rawurldecode($result['url']) == rawurldecode($url);

// or this
$result['isActive'] = Str::lower($result['url']) == Str::lower($url);
```

Later on [in the code](https://github.com/rainlab/pages-plugin/blob/23b9bc09ba48a8144c99698de296982d05f8c47e/classes/Page.php#L770), the same principle may be applied on nested items as well:

```php
// from this
$branchItem['isActive'] = $branchItem['url'] == $url;

// to this
$branchItem['isActive'] = rawurldecode($branchItem['url']) == rawurldecode($url);

// or this
$branchItem['isActive'] = Str::lower($branchItem['url']) == Str::lower($url);
```

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

**Comment by manuelbua** [comment]
Mmm just wondering.. since i'm noticing the "Abandoned" status crazyness.. what kind of activity would grant issues some love from your part? I mean, is it required for others to also confirm this, such as in #181, where i took the time to confirm? _Does the status indicates your posture with respect to the issue?_

Does any of you devs even **tried** to reproduce the issue? What's the point in asking for it from the beginning?

Closing down just because _"it has been over a month since any activity on this occurred"_ is complete non-sense to me..

**Comment by LukeTowers** [comment]
@manuelbua I'm going crazy with the Abandoned tag in order to prompt some movement with these issues. As it stands right now the core team is way too busy with everything to handle every single issue ourselves.

My solution to this is to poke people into actually taking on the issues that are important to them. If an issue isn't important to them anymore, then they won't do anything and everything will continue as it would have anyways. If it is still important to them, then this will act as a reminder that it still needs to be resolved and hopefully motivate people to try and dig deeper into the issue rather than just assume that the free support of an open source project will solve it for them.

In regards to this specific issue, I didn't even read your comment. It seems fairly well thought out to me though, so a pull request to fix the issue would be the next step to get this fixed.

Apologies if I've offended you, but there was simply no point in giving the impression that we would eventually dig deeper into this issue ourselves as we don't have the time to do so unless we run into it on our own. This is why I'm closing issues as abandoned, to actually get them solved.

**Comment by manuelbua** [comment]
Fair enough @LukeTowers, thanks for putting down the reasoning behind it: i'm not at all offended, in fact i proposed one solution and, not being a core dev, i would also expect for it to be normal to get rejected, for more than one reason and/or different assumptions, too bad discussion didn't kick in :(

I'm not the kind of guy who just assumes open source means everything is free, that's why i usually try to put in some concrete ideas where possible.

Sorry if i sounded harsh, that wasn't my intention: i can really see your point, and i'm wondering if adding a _Contributions needed_ tag could help to improve the situation.

**Comment by LukeTowers** [comment]
Perhaps, but I might just end up applying it to everything 😂 

As far as discussion on your suggestion goes, I like it as long as it solved the problem. The only thing I might suggest is adding a helper method to do the comparison for you in the Page.php class, perhaps something like `protected function checkItemActive($item, $currentUrl)` that would implement whatever correct checking works for unicode URLs.

**Comment by manuelbua** [comment]
Interesting idea, this would indeed centralize the solution logic in one place, avoiding littering the code and keeping it as DRY as possible.

**Comment by LukeTowers** [comment]
That's the idea. Feel free to make a PR implementing the fix and I'll review it.
