### ISSUE TITLE
Translation plugin bug when switching default locale

### ISSUE THREAD

**Issue by trnikon** [rainlab/pages-plugin#267]
Steps to reproduce:
1. Create two locales (let's say English and French, with English being default)
2. Make a new static page from the pages plugin. Fill the form and save.
3. Switch the default locale in Settings to French.
4. Open the static page you created in the back office and now the English values are shown as French

**Comment by jan-vince** [comment]
I think this is by design. Pages plugin is not dependent on Translate plugin. 

Static pages content is saved in ````content/static-pages````. With Translate plugin installed all translated versions are placed in 'locale' folders like ````content/static-pages-fr````, ````content/static-pages-en````.

I believe you can't think about default content as a 'translated one'. In fact it is 'non locale specific' (raw, untranslated) and you should create new locale for each language you need.

If you do not plan to switch default locale, let's 'pretend' the default content is in some locale.

But if you need to switch default locale, you have to add all languages as new and create specific content for them.

*@daftspunk will maybe make this more clear.*

**Comment by LukeTowers** [comment]
Great explanation @jan-vince, thanks for helping out!
