### ISSUE TITLE
Menu Item Duplicates

### ISSUE THREAD

**Issue by eleohner** [rainlab/pages-plugin#282]
When reordering a menu with the drag-and-drop feature, if you accidentally drop an item as a sub-item for another menu item, it will override the "Allow Nested Item" disabled functionality. 

Additionally, when dragging the item out of the submenu, the menu item it was accidentally dropped into will still have a dropdown on the frontend for the nest item, despite it no longer existing in that capacity.

**Comment by fuchsli** [comment]
In addition to this, upon deleting subpages, they still remain in the navigation, only they redirect to the 404 page.

**Comment by fuchsli** [comment]
Removing the submenu item entirely and allowing the nested children to be automatically added does fix the problem, but the problem subsists for non-children you want to add/remove from the menu.

**Comment by bennothommo** [comment]
@eleohner I have tested this with the latest version of the Pages plugin. I was unable to replicate any of the issues listed above, besides the "Allow Nested Item" functionality being disabled when a child item is added to that parent item. This is by design currently, as any explicitly provided child items of a menu item will overwrite the automatically generated nested items.

If you would like us to investigate the issues above further, please fill out an issue for each problem with steps to take in order for us to replicate the issue.
