### ISSUE TITLE
Cannot access placeholder tabs on lower resolution monitors if there are many

### ISSUE THREAD

**Issue by hushcode** [rainlab/pages-plugin#297]
The placeholder editor tab list does not seem to have horizontal scrolling, which causes some of the tabs to be inaccessible on lower resolution monitors  (i.e. 1366x768)

Here's a screenshot demonstrating the problem

![octobercms-pages-editor-placeholder-issue](https://user-images.githubusercontent.com/30935229/31315085-f7990af6-ac2d-11e7-95e5-07748a0f9996.jpg)

**Comment by jan-vince** [comment]
You can left click & drag to move tabs list.

*On my Mac I can also use horizontal scroll on my scrollbar or magic mouse.*

**Comment by LukeTowers** [comment]
I might also suggest that you should refactor your tabs, there shouldn't be a tab for every field.

**Comment by jonathan-hc** [comment]
I was the one who posted the original report. I converted the account to an organization after I posted, thus it appears as "ghost" now. 

@jan-vince That's really cool! I didn't realize, it could do that. My issue is fixed with the discovery of this feature. Just a suggestion: Maybe there should a tips or hints feature that introduces features like these that are not readily apparent to new users. 

@LukeTowers I am making this particular site from a ready-made theme, that has many discrete pieces of content surrounded by lots of layout related code.  The content will be ultimately edited using the WYSIWYG editor by end users who aren't that familiar with HTML markup.  If I were to use the default "Content" tab, then I would need to paste the entire layout code in there, which might leave open the possibility that a user will inadvertently delete some crucial layout related markup. Hence, I chose to go the "placeholder" route and make a placeholder for each piece of content on the page.

**Comment by LukeTowers** [comment]
@jonathan-hc I'm not saying that's a bad approach, I'm just saying that it could be organized better. You could look into putting multiple placeholders on each tab or better yet build a custom plugin that manages some of the more global information like ourClients or peopleHelped that would then have the markup generated by a plugin component without the chance of a user messing it up at all.
