### ISSUE TITLE
What is last version compatible with 419 build?

### ISSUE THREAD

**Issue by vdomah** [rainlab/pages-plugin#323]
I got one project that can't be updated up from 419 because of server restrictions. And pages plugin gives error Call to undefined method RainLab\Pages\Widgets\PageList::getCollapseStatus()
What commit I need to use to make Pages work with 419?

**Comment by LukeTowers** [comment]
https://github.com/rainlab/pages-plugin/commit/a938a5464a235a651b66f7153ee8f39924c940e1 is the last commit (in theory) because those methods were changed in the next commit: https://github.com/rainlab/pages-plugin/commit/86093035ba4fadaad0bf0677e800ce107f3cca0d. It is **highly** recommended that you solve your server restrictions however as there will be no future support for PHP < 7.0 at all.
