### ISSUE TITLE
Save repeaters in variable

### ISSUE THREAD

**Issue by dimensi** [rainlab/pages-plugin#328]
Hi! How save repeaters in variables? I want declare repeater and reuse it on layout.
Then i try call repeaters with one name but different mackup, repeaters stop working.

```
{# first repeator #}
      {repeater name="content_sections" prompt="Push" tab="Section" placement="primary"}
      <li>  {{ fields.title }} </li>
      {/repeater}
```
```
{# second repeator #}
      {repeater name="content_sections" prompt="Push" tab="Section" placement="primary"}
        {variable name="title" label="Title" type="text"}{/variable}
        {{ fields.title }}
        {richeditor name="content" label="Содержимое"}{/richeditor}
      {/repeater}
```
First repeator will be broken and not working, but second repeator still work.

**Comment by maartenmachiels** [comment]
Hi dimensi, I just posted another question here #336 
It possibly contains the answer to your question, as it contains an example of how to display the repeater values on the front-end. It might be worth checking out.

**Comment by bennothommo** [comment]
GitHub issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: https://octobercms.com/forum
StackOverflow: https://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or https://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
