### ISSUE TITLE
Make a connection to the user plugin

### ISSUE THREAD

**Issue by stefanreimert** [rainlab/pages-plugin#343]
Is there a way to make a connection to the user plugin so can pick a user from a dropdown list like you can with a blog author?

**Comment by LukeTowers** [comment]
You could do that by extending the classes/Page class in theory and adding a field for it, but this isn't really the place to discuss that. 

Github issues really isn't the place for questions like this. Please use one of the many other avenues available instead of submitting new issues for your questions.

Forum: http://octobercms.com/forum
StackOverflow: http://stackoverflow.com/questions/tagged/octobercms
IRC: #october on Freenode or http://octobercms.com/chat
Slack: https://octobercms-slack.herokuapp.com/
