### ISSUE TITLE
Connecting static pages to recordfinder

### ISSUE THREAD

**Issue by stefanreimert** [rainlab/pages-plugin#347]
When i use the following code i get the message in the image.
Can someone explain to me what this means?

![screen shot 2018-07-06 at 10 43 14](https://user-images.githubusercontent.com/4490250/42369175-73fd2ad6-8109-11e8-8d6b-c521edd237d6.png)

`        user:
            label: User
            span: left
            type: recordfinder
            list: $/rainlab/user/models/user/columns.yaml
            prompt: Click the %s button to find a user
            nameFrom: `name``

**Comment by LukeTowers** [comment]
@stefanreimert that's because the recordfinder uses a defined model level relation to work, you're going to have to use a dropdown instead. There has been some discussion on adding `modelClass` support to the recordfinder so it would work outside of direct relations (i.e. also in repeaters) but so far no work has been done in that regard. Feel free to submit a PR to the main October repo to introduce that functionality if you would like.

**Comment by bennothommo** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by LukeTowers** [comment]
Note: Support was added in https://github.com/octobercms/october/commit/920eb15af52446ece607e04149dadb511f350a54 to use the recordfinder without a model relationship, but I'm not sure this will work for this case as Pages are Halcyon models, not Eloquent models. You'd probably be better off using the PagePicker formwidget directly.
