### ISSUE TITLE
Unable to sort menu items when the box is scrolled down

### ISSUE THREAD

**Issue by vitty1** [rainlab/pages-plugin#384]
Hello,

I'm not able to sort menu item when there are more items and the box is scrolled down.

OctoberCMS version: 446
Static Pages version: 1.2.20
Tested in Firefox, Chrome

![menu sorting](https://user-images.githubusercontent.com/31191150/53418083-44691500-39d7-11e9-8897-6a4272d671b1.jpg)

**Comment by w20k** [comment]
Hi @vitty1, it's related to an old JS library. It's in my todo list, but don't know when will I be able to continue.

Same issue in sitemap: https://github.com/rainlab/sitemap-plugin/issues/66
Sortable plugin: https://github.com/johnny/jquery-sortable

**Comment by nleehone** [comment]
I'm having the same issue.

OctoberCMS version: 446
Static Pages version: 1.2.20
Tested in Chrome on Linux: Version 69.0.3497.100 (Official Build) (64-bit)

After a bit of testing I found that I could partially overcome the problem by setting
```
.control-scrollbar >div {
    -webkit-transform: none;
    -ms-transform: none;
    transform: none;
}
```
in Settings -> Customize back-end -> Styles.

This overrides the default style being applied, which is:
```
.control-scrollbar >div {
    -webkit-transform: translateZ(0);
    -ms-transform: translateZ(0);
    transform: translateZ(0);
}
```

With this change you can re-order the items if the destination is on-screen. This works because the stacking context of the absolutely positioned element was being set to the div under the control-scrollbar by `translateZ(0)`, which creates a new stacking context.

**Scrolling still causes issues, because scrolling doesn't affect the `top` position of the absolutely positioned element.** If you need to move an element to a position that is off-screen, then do the move in multiple steps, scrolling in-between moves, not during the move.

I'm going to look into this further and see if there is a way to get the js to update the position correctly on scroll.

**Comment by nleehone** [comment]
Another quick update.

If you scroll using the mouse button, the problem mentioned in my previous post persists, _however if you scroll by dragging the item to the top or bottom of the screen the the above fix works._

I'm still not sure what is causing the mouse scroll to work differently than dragging the item to the top or bottom of the screen.

**Comment by LukeTowers** [comment]
@nleehone are you able to make a PR with a fix to this?

**Comment by nleehone** [comment]
I still haven't managed to fix the issue with the mouse scroll wheel, so it wouldn't be a complete fix - it would only address the problem when dragging the item without scrolling.

If this is acceptable then I will look into how to make a PR (never done this before).

**Comment by bennothommo** [comment]
@nleehone Would you mind starting a PR with the fix so far? You will need to fork the Pages plugin repo and then [follow the steps here](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) in order to make a pull request from your fork.

**Comment by w20k** [comment]
@bennothommo what I've found out, that we need to fix old  https://github.com/johnny/jquery-sortable plugin to make it work. So, I'd say it's a core issue.

**Comment by daftspunk** [comment]
Mouse scroll wheel fix: https://github.com/octobercms/october/commit/ed2eec6afb97141003c443586e6370d379e2dc5c

CSS fix:
https://github.com/octobercms/october/commit/0a98afbff8b78d4a3f6e144124c4649003bf4334

This should be fixed in Build 462+
