### ISSUE TITLE
Upgrade broke our site

### ISSUE THREAD

**Issue by cityofroseburg** [rainlab/pages-plugin#410]
We updated pages and now our site will not load.  http://tta.haf.mybluehost.me  

We are testing this site before we roll it over to live and now it will not load after the 1.3.0 today.

![Capture](https://user-images.githubusercontent.com/55157330/64639006-c8a34880-d3bb-11e9-9204-3799d576dadd.JPG)

**Comment by LukeTowers** [comment]
You updated the plugin without updating the core. Your site has `cms.disableCoreUpdates` set to true because it's setup to manage the updates via composer instead. Either login via the terminal and run `composer update` in the website root or send me the credentials via email and I'll take care of it.
