### ISSUE TITLE
How can I link to another static page without hardcoding the URL?

### ISSUE THREAD

**Issue by emzero** [rainlab/pages-plugin#43]
Is there a way to add an hyperlink in a static page to another via name/id without hardcoding the url? So that if I change the slug of the linked page, the link still works.

Thanks

**Comment by daftspunk** [comment]
Added this for you in 754473f27e260a29672cda461f5b20261aa237f7

Docs updated with:

##### Linking to static pages

When a static page is first created it will be assigned a file name based on the URL. For example, a page with the URL **/chairs** will create a content file called **static-pages/chairs.htm** in the theme. This file will not change even if the URL is changed at a later time.

To create a link to a static page, use the `|staticPage` filter:

    <a href="{{ 'chairs'|staticPage }}">Go to Chairs</a>

This filter translates to PHP code as:

    echo RainLab\Pages\Classes\Page::url('chairs');

If you want to link to the static page by its URL, simply use the `|app` filter:

    <a href="{{ '/chairs'|app }}">Go to Chairs</a>

**Comment by emzero** [comment]
Great, thanks!

**Comment by emzero** [comment]
By the way, I see the documentarion here is much more complete than the one in: http://octobercms.com/plugin/rainlab-pages

Maybe you should link to the one here in the october cms plugin page.

**Comment by maartenmachiels** [comment]
Is there any way to get this functionality working with the Translate plugin? My goal is not to hardcode the urls (since the client can change them), but to get the right url relative to the current locale. 

The "chairs" page (/en/chairs) for example would be "chaises" (/fr/chaises) in french. 
So in my code I'd like to do something like this:

`<a href="{{ '/chairs'|app }}">{{ 'Go to chairs page' | _ }}</a>`

Since October remembers the activelocale in the session, depending on the chosen language the output would be:

`<a href="/en/chairs/">Go to chairs page</a>`

or

`<a href="/fr/chaises/">Aller vers la page de chaises</a>`

How would we be able to do this? Might we find the translated, relative url by looking it up via its layout? What would the code look like?

**Comment by LukeTowers** [comment]
@maartenmachiels you should just be able to use the staticPage filter on the filename instead

**Comment by maartenmachiels** [comment]
Thanks Luke, I was able to use your suggestions and solve it. The filename is the name of the generated staticPage file in the `/content` folder, without the `.htm` suffix, as described here: [https://octobercms.com/plugin/rainlab-pages](https://octobercms.com/plugin/rainlab-pages), segment "Linking to static pages". I was looking for this for a while, it's great!
