### ISSUE TITLE
Image insert new features.

### ISSUE THREAD

**Issue by mkinternet** [rainlab/pages-plugin#444]
Static page image edit function should have some new features

- edit or create alt attribute
- edit or create title attribute
- edit or create class attribute.

**Comment by bennothommo** [comment]
@mkinternet Do you mean images added to the Rich Editor, or do you mean images added to fields somewhere else?

**Comment by mkinternet** [comment]
Images added to the richeeditor

https://pasteboard.co/JivUcqZ.png

**Comment by bennothommo** [comment]
@mkinternet Ah yep, I see. I believe if we wanted full control over those attributes, we need to do it through plugins to the Rich Editor (Froala) widget itself - unfortunately, this is a challenge due to it being proprietary software. It's something we can look at down the line, but for now, you'll probably have to add those attributes through the Code Editor action in the Rich Editor.

**Comment by daftspunk** [comment]
This is possible in the latest version.

- Alt text can be set via "Info"
- Class can be set via "Style"
- Title-like attribute can be set via "Image Caption"

Thanks!
