### ISSUE TITLE
Many items in repeater break admin interface (loading 4 ever)

### ISSUE THREAD

**Issue by renickbuettner** [rainlab/pages-plugin#472]
- OctoberCMS Build: 471
- RainLab Pages Plugin Version: 1.3.6
- PHP Version: 7.4

### Description:
On my new layout, there are three repeaters. Each represent a subject, and include a child repeater for adding contact persons. I created some subjects and foreach 5-10 contacts (Name + Email + Phone). I saved it successfully. But when I want to re-open the page, it needs 2-3 minutes for opening the page (only on backend side). In frontend, it displays the data rapidly.

When the page got loaded after a long time, I can edit the data without a lag. May there's something going on in the rendering of the YAML to the repeater fields? Can I do something to improve admin page load? 

More memory hasn't help, I really had to increase the max script load time. Tested locally, as well as on 24-core web server.

### Steps To Reproduce:
- Create repeater with child repeater
- Add 5 x 10 entries with Email, Phone (not rich text)
- Save Static Page
- Reload Admin Backend, re-open the page
- Grab a coffee, and watch [OVH datacenter burn](https://techlog360.com/cloud-host-ovh-data-center-burned-down/) 🙈  (jk, sorry for that one)

I really know, that we may can do this with Builder and a data-table, but I tried to use the flexibility of Static Page (which is amazing ❤️). Till now I never had a slow Static Page in the admin backend.

**Comment by daftspunk** [comment]
Seems like this could be caused by recursion somewhere between the code and your implementation. We could look into this for you, however, we estimate it may take some hours to discover the issue. We have a premium support program that can help with these types of more complex issues: https://octobercms.com/premium-support

Alternatively, if you are able to trace the code and find where the fault occurs, we would happily accept a pull request to address it. Another option would be to use Builder, this is certainly a more robust solution. Just ping me in this ticket if you'd like it to be reopened with have some more information

Thanks for using October CMS! 🙏
