### ISSUE TITLE
Problem with backend editor

### ISSUE THREAD

**Issue by vilfullstack** [rainlab/pages-plugin#473]
I'm building an theme with uikit framework, but some components use att like:

`<div class = "uk-grid-small" uk-grid>`

The problem is that the Statics Page removes att uk-grid when I edit the page content in the backend.

`<div class = "uk-grid-small">`

Is there any way to fix the above problem?
Thanks for listening.

**Comment by daftspunk** [comment]
It would appear that you've bumped into [a very old issue](https://github.com/octobercms/october/issues/2576), and only the following attributes are allowed according to a whitelist: 

`
['accept', 'accept-charset', 'accesskey', 'action', 'align', 'allowfullscreen', 'allowtransparency', 'alt', 'aria-.*', 'async', 'autocomplete', 'autofocus', 'autoplay', 'autosave', 'background', 'bgcolor', 'border', 'charset', 'cellpadding', 'cellspacing', 'checked', 'cite', 'class', 'color', 'cols', 'colspan', 'content', 'contenteditable', 'contextmenu', 'controls', 'coords', 'data', 'data-.*', 'datetime', 'default', 'defer', 'dir', 'dirname', 'disabled', 'download', 'draggable', 'dropzone', 'enctype', 'for', 'form', 'formaction', 'frameborder', 'headers', 'height', 'hidden', 'high', 'href', 'hreflang', 'http-equiv', 'icon', 'id', 'ismap', 'itemprop', 'keytype', 'kind', 'label', 'lang', 'language', 'list', 'loop', 'low', 'max', 'maxlength', 'media', 'method', 'min', 'mozallowfullscreen', 'multiple', 'muted', 'name', 'novalidate', 'open', 'optimum', 'pattern', 'ping', 'placeholder', 'playsinline', 'poster', 'preload', 'pubdate', 'radiogroup', 'readonly', 'rel', 'required', 'reversed', 'rows', 'rowspan', 'sandbox', 'scope', 'scoped', 'scrolling', 'seamless', 'selected', 'shape', 'size', 'sizes', 'span', 'src', 'srcdoc', 'srclang', 'srcset', 'start', 'step', 'summary', 'spellcheck', 'style', 'tabindex', 'target', 'title', 'type', 'translate', 'usemap', 'value', 'valign', 'webkitallowfullscreen', 'width', 'wrap']
`

You'd need to add `uk-.*` to that list. Currently, there is no native method for doing so. However, it is possible if you can add this JavaScript in to your backend layout somewhere

```
+function ($) { "use strict";
    $(document).render(function() {
        if ($.FroalaEditor) {
            $.FroalaEditor.DEFAULTS = $.extend($.FroalaEditor.DEFAULTS, {
                htmlAllowedAttrs: $.extend($.FroalaEditor.DEFAULTS.htmlAllowedAttrs, ['uk-.*'])
            });
        }        
    })
}(window.jQuery);
```

I have also included this functionality in the upcoming October CMS release. Use the above instructions if you cannot wait. Otherwise, the release should be available pretty soon.

![image](https://user-images.githubusercontent.com/1392869/111057017-3ad87a00-84d8-11eb-94bc-f85ccd50f0f5.png)

Look out for this UI in the next October CMS release under Settings > Editor Settings ^ Thanks for reporting this 🙏
