### ISSUE TITLE
Modified layout not found

### ISSUE THREAD

**Issue by andrealune** [rainlab/pages-plugin#480]
- OctoberCMS Build: 2.0.17
- RainLab Pages Plugin Version: 1.4.3
- PHP Version: 7.4.12

### Description:
When i add the static page component to my layout and save, i get the error:

"Argument 1 passed to RainLab\Pages\Classes\Router::__construct() must be an instance of Cms\Classes\Theme, string given, called in /Users/secret/Web/4linee/sportydog/plugins/rainlab/pages/Plugin.php on line 247" on line 39 of /Users/secret/Web/4linee/sportydog/plugins/rainlab/pages/classes/Router.php

When i open the plugin section (backend/rainlab/pages) I get the error **Modified layout not found**

I checked cms.active_theme value and it's correct, also the value cms/theme/edit value in the table _backend_user_preferences is correct  too.

### Steps To Reproduce:
- Run php artisan plugin:install rainlab.pages
- Add Static pages component to your theme layout

**Comment by daftspunk** [comment]
Hey there,

Hmm, interesting that I'm not getting the same result. Also interesting because the typehinting in the code should not even allow a string to be passed.

Can you try resetting the Edit theme in the Editor by selecting the theme menu (+ ...) > Edit Theme > (select your theme)

Tested with 2.0.17 core, Pages 1.4.3 and PHP 8.0.3
