### ISSUE TITLE
Class_parents(): Class undefined does not exist and could not be loaded

### ISSUE THREAD

**Issue by LZaplata** [rainlab/pages-plugin#515]
Hello,

- OctoberCMS Build: 3.1.28
- RainLab Pages Plugin Version: 1.5.6
- PHP Version: 8.1

### Description:
I have just upgraded OctoberCMS from v2 to v3 and found multiple problems with component snippet. Now when I want to add snippet to a page and click on snippet in snippets list, nothing happened and snippet is not added to a page, in v2 was. Second problem occurred when I click on snippet in page (snippet is in page from v2), see screenshot below.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/12596881/209178196-c9851d68-b725-4192-a7f7-86e17722135b.png">

Snippet is registered and everything was OK in v2. I can add component to CMS page without any problem.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/12596881/209178788-b519a107-e0a6-4bdf-b4bb-c3388cc20c48.png">

Is it bug or is there something I need to change after upgrade? Thank for your answer.

**Comment by daftspunk** [comment]
Hi @LZaplata,

To confirm we cannot reproduce this issue using the [test plugin](https://github.com/octobercms/test-plugin). In most cases these errors are caused by the new Laravel version and some incompatible plugin. Check the error logs in storage/logs/ to see if there is a more detailed stack trace.

```
public function registerPageSnippets()
{
    return [
        \October\Test\Components\KitchenSink::class => 'KitchenSink'
    ];
}
```

Otherwise, feel free to contact us here for personalized support with this issue: https://octobercms.com/contact
