### ISSUE TITLE
How to insert content blocks?

### ISSUE THREAD

**Issue by tbergeron** [rainlab/pages-plugin#54]
Hi, I'm trying to insert a content block like this:

`{% content 'contacts.htm' %}`

as mentioned here:
http://octobercms.com/docs/cms/content#rendering-content-blocks

What am I doing wrong? Is there a diffrent syntax for this plugin?

Thanks

**Comment by felixinx** [comment]
Hi,

You can't  render content in the static-pages plugins.

Sorry about that.

Félix Desjardins

**Comment by tbergeron** [comment]
But why is there a content tab in your plugin then?

Thanks for your quick response!

**Comment by felixinx** [comment]
Because the static-pages is actually a *content*! The plugin **can't** render any `content, translate tag` or other thing like this. Check #32

**Comment by hybridvision** [comment]
As Félix says, the static-pages are not the same as the CMS pages referred to in the core documentation - they are much simpler (no code section for a start).

If you need to render a content block within a static page, you might need to create a component/snippet to handle this. The snippet could take the name of the content file and return the contents or it could be made very specific, depending on your needs. It shouldn't be too hard to implement if you read up on how to use snippets.

I think the reason there is a 'content' tab in the static pages plugin is to allow lower-level users the ability to edit these content blocks easily. For example, I have a site using October where I've given the client access to the static pages in the CMS but not to the main CMS pages because they could potentially break the site with that. This setup is good because they can edit normal pages, choose layouts and even update special content blocks without ever having to leave the visual editor.

Hope that helps!

**Comment by tbergeron** [comment]
This makes much more sense @hybridvision thanks I get why it's that way now.

Basically what I'm attempting to do is a fully bilingual website. I want my clients to be able to easily modify any content in any languages but OctoberCMS/Translate makes it a bit hard to do so. I tried those:

1) Created basic page with content block in it, content blocks are named like this: home.fr.htm, home.en.htm so clients can modify those content file without touching the page itself. The problem: page titles are hardcoded and not translate so the content is localized but not the title. I have the menus manager plugin which is translatable as well so only page titles are not localized.

2) I tried this plugin but it's not localized yet (I see it's a work in progress so I'm totally cool with waiting for better feature)

3) I tried to use the home.fr.html/home.en.htm file syntax with pages instead of content blocks but it didn't worked.

Any idea on how to properly implement a multi lingual websites?

Thanks a lot
3)

**Comment by tbergeron** [comment]
Here's an example of a translated page with the title not working: http://octobercms.brainpad.org/about-us

The page content is:
`{% content 'about-us.htm' %}`

And I have about-us.fr.htm and about-us.en.htm that automatically gets picked by Translatable. I'd like the same to happen for pages or if anyone could enlighten me about this hehe thx

**Comment by felixinx** [comment]
Attend, les deux pages présentes sur ton site **ne font pas parti du plugin `Rainlab.Pages`**. Pourquoi? Elles sont traduites, ce qui est impossible pour l'instant, *voir #32*. Si il y a un problème avec ces pages, ca serait à poster directement dans [octobercms/october](http://github.com/octobercms/october).
