### ISSUE TITLE
WYSIWYG Compatibility

### ISSUE THREAD

**Issue by marcoelho97** [rainlab/pages-plugin#82]
This plugin's WYSIWYG is quite bad, to be honest, so, I went to look for a way around, being that way the plugin WYSIWYG Editor. Unfortunately they don't seem to match because they go all buggy like. Text editor shows up really down sized and either it takes a real long while to load, or doesn't load the "page"!! If I double click though, it goes buggy and opens, but still a matter to see, in my opinion :+1:

**Comment by hybridvision** [comment]
I agree that there is plenty of room for improvement in the WYSIWYG editor and I also experimented with replacing the default editor via the [plugin](http://octobercms.com/plugin/anandpatel-wysiwygeditors) but it seems to be even more fragile and hasn't been updated for several months...

The main problem with replacing the default editor is that you then lose the snippets and placeholder functionality, which is a pretty major downside.

Rather than attempting to replace the standard editor, I think it's better to try to address any specific problems. I know the October developers have a heap of features they're working on and they have already been improving the editor but you can help by raising tickets for specific bugs or feature ideas you have...

**Comment by FelixINX** [comment]
Hi,

**The WYSIWG plugin does not come from the plugin, or October. It's [RedactorJS](http://redactorjs.com/) and any option can be set from October core.**

But, a compatibility of other editor could be nice, but too complex, because of the choice.

**Comment by msimkunas** [comment]
What's so bad about the default WYSIWYG editor? It looks and behaves pretty well as far as I'm concerned.

**Comment by daftspunk** [comment]
Fixed by https://github.com/octobercms/october/issues/2005
